### ISSUE TITLE
request for [pdf] of  the subpixel edge location algorithm 

### ISSUE THREAD

**Issue by Roger8** [gravi-toni/subpixel-edges#3]
hi @gvitucci  , i got to know the subpixel edge location algorithm from mathworks file exchange website , then i found your repos implemented by python which was wonderful.  I want to learn the detail of the algorithm , but the thing is that i cannot get a pdf document of the algorithm . If it is convinent i want a pdf copy of it. Looking forward to your reply .
Best wishes to u. .

**Comment by gvitucci** [comment]
Hi, 
you can find the draft of the paper here:

_https://www.researchgate.net/profile/Agustin-Trujillo-Pino/publication/233397974_Accurate_Subpixel_Edge_Location_based_on_Partial_Area_Effect/links/5a932f910f7e9ba4296f4bfb/Accurate-Subpixel-Edge-Location-based-on-Partial-Area-Effect.pdf?origin=publication_detail_

-GV
